### ISSUE TITLE
[feature request] edit drafts

### ISSUE THREAD

**Issue by aMOPel** [pimalaya/himalaya-vim#11] opened 2024-10-04 07:17 UTC
I did not find a convenient way to edit drafts.

When in a draft folder, you can only open drafts in read-only mode or compose a new empty email. This makes sense for all other folders, but for the draft folder some special behaviour would make sense I believe. 

E.g. a mapping to copy the content of the email under the cursor to a new empty email buffer, would suffice.

**Comment by soywod** [comment] 2024-10-04 07:41
Duplicate of https://github.com/pimalaya/himalaya/issues/476, the draft management needs definitely a refactor. The editing feature is a must.

**Closed by soywod** 2024-10-04 07:41 UTC
